// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OilProduction.Persistence.Data;

#nullable disable

namespace OilProduction.Persistence.Migrations
{
    [DbContext(typeof(OilProductionDbContext))]
    [Migration("20260519220232_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Crop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("HarvestedDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<double>("ProductionQuantity")
                        .HasColumnType("float");

                    b.Property<long>("TreeFarmId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeFarmsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TreeFarmsId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Description", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<double>("Nut1Amount")
                        .HasColumnType("float");

                    b.Property<long>("Nut1Id")
                        .HasColumnType("bigint");

                    b.Property<double>("Nut2Amount")
                        .HasColumnType("float");

                    b.Property<long>("Nut2Id")
                        .HasColumnType("bigint");

                    b.Property<double>("Nut3Amount")
                        .HasColumnType("float");

                    b.Property<long>("Nut3Id")
                        .HasColumnType("bigint");

                    b.Property<double>("Nut4Amount")
                        .HasColumnType("float");

                    b.Property<long>("Nut4Id")
                        .HasColumnType("bigint");

                    b.Property<double>("Nut5Amount")
                        .HasColumnType("float");

                    b.Property<long>("Nut5Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Nut1Id");

                    b.HasIndex("Nut2Id");

                    b.HasIndex("Nut3Id");

                    b.HasIndex("Nut4Id");

                    b.HasIndex("Nut5Id");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Diseases", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.DiseasesCrops", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CropId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("DiseaseId")
                        .HasColumnType("bigint");

                    b.Property<long>("DiseasesId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("DiseasesId");

                    b.ToTable("DiseasesCrops");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Meal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<double>("TotalMealProduction")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Nutriens", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nutriens");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.PressOrders", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CropId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<long>("MealId")
                        .HasColumnType("bigint");

                    b.Property<double>("OrderQuantity")
                        .HasColumnType("float");

                    b.Property<long>("PressId")
                        .HasColumnType("bigint");

                    b.Property<long>("PressesId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("MealId");

                    b.HasIndex("PressesId");

                    b.ToTable("PressOrders");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Presses", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Presses");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Soil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Soils");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Farm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("FarmerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SoilId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.HasIndex("SoilId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Farmer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adderss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Fertilizers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("DescriptionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OldestTestAge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId");

                    b.ToTable("Fertilizers");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Tree", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.TreeFarmFertilizer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("FertilizerId")
                        .HasColumnType("bigint");

                    b.Property<long>("FertilizersId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<long>("TreeFarmId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreesFarmsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FertilizersId");

                    b.HasIndex("TreesFarmsId");

                    b.ToTable("TreeFarmFertilizers");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.TreeFarmTeam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AmountCollected")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCrop")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreeFarmId")
                        .HasColumnType("bigint");

                    b.Property<long>("TreesFarmsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TreesFarmsId");

                    b.ToTable("TreeFarmTeams");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.TreesFarms", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePlanted")
                        .HasColumnType("datetime2");

                    b.Property<long>("FarmId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<long>("TreeId")
                        .HasColumnType("bigint");

                    b.Property<int>("TreeSpacing")
                        .HasColumnType("int");

                    b.Property<double>("UsedPersentage")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("TreeId");

                    b.ToTable("TreesFarms");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.Weather.WeatherConditions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateRecorded")
                        .HasColumnType("date");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<double>("RaindLevel")
                        .HasColumnType("float");

                    b.Property<double>("WindLevel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("WeatherConditions");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.Weather.WeatherCrops", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CropId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<long>("WeatherId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("WeatherId");

                    b.ToTable("WeatherCrops");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.TeamWork", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsManeger")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("WorkId");

                    b.ToTable("TeamWorks");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.TeamWorkJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long?>("JobId1")
                        .HasColumnType("bigint");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TeamId1")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobId1");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId1");

                    b.HasIndex("WorkId");

                    b.HasIndex("WorkId1");

                    b.ToTable("TeamWorkJobs");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.Work", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Crop", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.FarmTree.TreesFarms", "TreeFarms")
                        .WithMany("Crops")
                        .HasForeignKey("TreeFarmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TreeFarms");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Description", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.CropLand.Nutriens", "Nutrien1")
                        .WithMany()
                        .HasForeignKey("Nut1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.CropLand.Nutriens", "Nutrien2")
                        .WithMany()
                        .HasForeignKey("Nut2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.CropLand.Nutriens", "Nutrien3")
                        .WithMany()
                        .HasForeignKey("Nut3Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.CropLand.Nutriens", "Nutrien4")
                        .WithMany()
                        .HasForeignKey("Nut4Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.CropLand.Nutriens", "Nutrien5")
                        .WithMany()
                        .HasForeignKey("Nut5Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nutrien1");

                    b.Navigation("Nutrien2");

                    b.Navigation("Nutrien3");

                    b.Navigation("Nutrien4");

                    b.Navigation("Nutrien5");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.DiseasesCrops", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.CropLand.Crop", "Crop")
                        .WithMany("DiseasesCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.CropLand.Diseases", "Diseases")
                        .WithMany("DiseasesCrops")
                        .HasForeignKey("DiseasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Diseases");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.PressOrders", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.CropLand.Crop", "Crop")
                        .WithMany("PressOrders")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.CropLand.Meal", "Meal")
                        .WithMany("PressOrders")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.CropLand.Presses", "Presses")
                        .WithMany("PressOrders")
                        .HasForeignKey("PressesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Meal");

                    b.Navigation("Presses");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Farm", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.FarmTree.Farmer", "Farmer")
                        .WithMany("Farms")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.CropLand.Soil", "Soil")
                        .WithMany("farms")
                        .HasForeignKey("SoilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Soil");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Fertilizers", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.CropLand.Description", "Description")
                        .WithMany()
                        .HasForeignKey("DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Description");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.TreeFarmFertilizer", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.FarmTree.Fertilizers", "Fertilizers")
                        .WithMany("TreeFarmFertilizers")
                        .HasForeignKey("FertilizersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.FarmTree.TreesFarms", "TreesFarms")
                        .WithMany("TreeFarmFertilizers")
                        .HasForeignKey("TreesFarmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fertilizers");

                    b.Navigation("TreesFarms");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.TreeFarmTeam", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Team", "Team")
                        .WithMany("TreeFarmTeam")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.FarmTree.TreesFarms", "TreesFarms")
                        .WithMany("TreeFarmTeams")
                        .HasForeignKey("TreesFarmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("TreesFarms");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.TreesFarms", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.FarmTree.Farm", "Farm")
                        .WithMany("TreesFarms")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.FarmTree.Tree", "Tree")
                        .WithMany("TreeFarmsT")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.Weather.WeatherCrops", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.CropLand.Crop", "Crop")
                        .WithMany("WeatherCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.Weather.WeatherConditions", "Weather")
                        .WithMany("WeatherCrops")
                        .HasForeignKey("WeatherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Weather");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.TeamWork", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Team", "Team")
                        .WithMany("TeamWork")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Work", "Work")
                        .WithMany("TeamWorks")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.TeamWorkJob", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Job", null)
                        .WithMany("TeamWorkJobModels")
                        .HasForeignKey("JobId1");

                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Team", null)
                        .WithMany("TeamWorkJobs")
                        .HasForeignKey("TeamId1");

                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Work", null)
                        .WithMany("TeamWorkJobModels")
                        .HasForeignKey("WorkId1");

                    b.Navigation("Job");

                    b.Navigation("Team");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.Work", b =>
                {
                    b.HasOne("OilProduction.Domain.Entities.WorkTeam.Job", "Job")
                        .WithMany("Works")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Crop", b =>
                {
                    b.Navigation("DiseasesCrops");

                    b.Navigation("PressOrders");

                    b.Navigation("WeatherCrops");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Diseases", b =>
                {
                    b.Navigation("DiseasesCrops");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Meal", b =>
                {
                    b.Navigation("PressOrders");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Presses", b =>
                {
                    b.Navigation("PressOrders");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.CropLand.Soil", b =>
                {
                    b.Navigation("farms");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Farm", b =>
                {
                    b.Navigation("TreesFarms");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Farmer", b =>
                {
                    b.Navigation("Farms");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Fertilizers", b =>
                {
                    b.Navigation("TreeFarmFertilizers");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.Tree", b =>
                {
                    b.Navigation("TreeFarmsT");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.FarmTree.TreesFarms", b =>
                {
                    b.Navigation("Crops");

                    b.Navigation("TreeFarmFertilizers");

                    b.Navigation("TreeFarmTeams");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.Weather.WeatherConditions", b =>
                {
                    b.Navigation("WeatherCrops");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.Job", b =>
                {
                    b.Navigation("TeamWorkJobModels");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.Team", b =>
                {
                    b.Navigation("TeamWork");

                    b.Navigation("TeamWorkJobs");

                    b.Navigation("TreeFarmTeam");
                });

            modelBuilder.Entity("OilProduction.Domain.Entities.WorkTeam.Work", b =>
                {
                    b.Navigation("TeamWorkJobModels");

                    b.Navigation("TeamWorks");
                });
#pragma warning restore 612, 618
        }
    }
}
